name: Build docker images

on:
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Build docker images
      run: docker build -t test .
      
